const questionList = {
  1: "GitHub user search component",
  2: "Todo List Application",
  3: "Password Strength Checker",
  4: "Infinite Scroll Component",
  5: "Shopping Cart Component",
  6: "Multi-Step Form Wizard",
  7: "Accordion Component",
  8: "Product Search & Filter Dashboard",
  9: "Autocomplete Search Component",
  10: "Multi-Tab Form Component",
  11: "Calculator",
  12: "Pagination",
  13: "Countdown Timer",
  14: "Dismissible Modal Overlay",
  15: "Mortgage calculator",
  16: "Carousel Component",
  17: "Two-factor Code Input",
  18: "File Folder Explorer",
  19: "Star Rating Component",
  20: "Transfer List Component",
  21: "Progress Bar Component",
  22: "Tic Tac Toe",
  23: "Memory Game",
  24: "HackerNews Job Board",
  25: "Nested Comments",
  26: "Crypto converter",
};

export default questionList;
