export const data = [
  { title: "Bold", id: 0, checked: false },
  { title: "Italic", id: 1, checked: false },
  { title: "Underline", id: 2, checked: false },
  { title: "Font Color", id: 3, checked: false },
  { title: "Text Highlight Color", id: 4, checked: false },
  { title: "Align Left", id: 5, checked: false },
  { title: "Align Center", id: 6, checked: false },
  { title: "Align Right", id: 7, checked: false },
  { title: "Justify", id: 8, checked: false },
  { title: "Bullets", id: 9, checked: false },
  { title: "Numbering", id: 10, checked: false },
  { title: "Increase Indent", id: 11, checked: false },
  { title: "Decrease Indent", id: 12, checked: false },
  { title: "Line Spacing", id: 13, checked: false },
  { title: "Styles", id: 14, checked: false },
  { title: "Find", id: 15, checked: false },
  { title: "Replace", id: 16, checked: false },
];
